server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_service
    username: order_user
    password: order_pw
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: order-service
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs/app-api-docs